[package]
name = "rustexperiment"
version = "0.1.0"
authors = ["kamp <nbvdkamp@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
stats = []

[dependencies]
impl_ops = "0.1.1"
cgmath = "0.18.0"
image = "0.23.14"
rand = "0.8.4"
crossbeam = "0.8.1"
num_cpus = "1.13.1"
lerp = "0.4.0"
clap = "3.1.6"

glfw = "0.44.0"

luminance = "0.47.0"
luminance-derive = "0.10.0"
luminance-front = "0.6.1"
luminance-glfw = "0.18.2"
luminance-windowing = "0.10.1"

[dependencies.gltf]
version = "1.0.0"
features = [
    "KHR_lights_punctual",
    "KHR_materials_transmission",
    "KHR_materials_ior",
]

[dependencies.rgb2spec-rs]
path = "../rgb2spec-rust"