[package]
name = "bench"
version = "0.1.0"
authors = ["kamp <nbvdkamp@gmail.com>"]
edition = "2021"

[features]
stats = []


[dependencies]
renderer = { path = "../renderer" }
cgmath = { workspace = true }
num_cpus = { workspace = true }
